### PR TITLE
sd_decrypt.py and Requirements file

### PR DESCRIPTION
**Pull request by RickAfon**
Added Counter (Cryptodome.Util) to the imported libs that was missing and added a "Requirements" text file.

### CODE REVIEW

**Comment by wwylele** [comment]
Thanks for the PR!

About the requirements text file:
 - it shows up as binary file in github. Could you check if it has weird encoding or anything? like is it UTF-16 or UTF-8 with BOM? I recommend using BOM-less UTF8 (and because this is ASCII only, you are safe to just use the ANSI option in notepad if you are on Windows)
 - the repo only needs one of `﻿pycryptodome` or `pycryptodomex`. We can specify just one, right?

**Comment by RickAfon** [comment]
I will try to fix that.

**Comment by RickAfon** [comment]
Sorry for the delay, still learning how to use this platform. This PR was made because the "Counter" was missing and I couldn't use the program. I don't know if it had a better way to notify you, at least I tried.

**Comment by wwylele** [comment]
No problem, and thank you! The code looks good to me now. I am going to merge soon

**Pull request merged**
